version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py  # Mount the Flask app file (change this path as needed)
  nginx:
    image: nginx:latest
    ports:
      - "81:81"  # Change port 80 to 81 for the Nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf