version: '3'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - target: 5000
        published: 5000
    volumes:
      - ./app.py:/app/app.py  # Mount the Flask app file (change this path as needed)
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind mount the nginx.conf file
